version: '3.7'

volumes:
  db-data:

networks:
  instavote:
    driver: bridge

services:
  vote:
    image: chuckchastain/vote:main
    build: ./vote
    ports: 
      - 5000:80
    depends_on:
      - redis
    networks:
      - instavote

  redis:
    image: redis:alpine
    networks:
      - instavote
    
  db:
    image: postgres:9.4
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - instavote
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  result:
    image: chuckchastain/result:main
    build: ./result
    ports: 
      - 5001:4000
    depends_on:
      - db
    networks:
      - instavote
        
  worker:
    image: chuckchastain/worker:main
    build: ./worker
    depends_on:
      - redis
      - db
    networks:
      - instavote
